apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-deploy-pod
  namespace: default
spec:
  params:
  - name: action
    description: Action on the resource
  - name: merge-strategy
    default: strategic
    description: Merge strategy when using action  patch
  - name: manifest
    description: Content of the resource to deploy
  - name: success-condition
    default: ""
    description: A label selector express to decide if the action on resource is success.
  - name: failure-condition
    default: ""
    description: A label selector express to decide if the action on resource is failure.
  - name: output
    default: ""
    description: An express to retrieval data from resource.
  - name: set-ownerreference
    default: "false"
    description: Enable set owner reference for created resource.
  - name: image
    default: index.docker.io/vincentpli/kubeclient:v0.0.21 # it is huge
    description: Kubectl wrapper image
  - name: monitor-interval
    default: "5"
    description: Monitor interval(second) when decide resource status by 'success-condition' and 'failure-condition'.
  - name: monitor-count
    default: "3"
    description: Monitor count(default return immediately when meet) when decide resource status by 'success-condition' and 'failure-condition'.
  steps:
  - name: kubeconfig
    image: $(params.image)
    args:
      - --action=$(params.action)
      - --merge-strategy=$(params.merge-strategy)
      - --manifest=$(params.manifest)
      - --success-condition=$(params.success-condition)
      - --failure-condition=$(params.failure-condition)
      - --output=$(params.output)
      - --set-ownerreference=$(params.set-ownerreference)
      - --monitor-interval=$(params.monitor-interval)
      - --monitor-count=$(params.monitor-count)
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_UID
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid
  - name: echo
    image: busybox
    script: |
      #!/bin/sh
      if [ -e /tekton/results/job-name ]
      then
          cat /tekton/results/job-name
      else
          echo "no output file found"
      fi

