apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kubectl-deploy-pod
  namespace: default
spec:
  inputs:
    params:
    - name: action
      description: Action on the resource
    - name: merge-strategy
      default: strategic
      description: Merge strategy when using action  patch
    - name: manifest
      description: Content of the resource to deploy
    - name: image
      default: index.docker.io/vincentpli/kubeclient:v0.0.21 # it is huge
      description: Kubectl wrapper image
  steps:
  - name: kubeconfig
    image: $(inputs.params.image)
    args:
      - --action=$(inputs.params.action)
      - --merge-strategy=$(inputs.params.merge-strategy)
      - --manifest=$(inputs.params.manifest)
