apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: kubectl-delete-pod
spec:
  taskRef:
    name: kubectl-deploy-pod
  inputs:
    params:
    - name: action
      value: delete
    - name: manifest
      value: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: myapp-pod
          labels:
            app: myapp
        spec:
          containers:
          - name: myapp-container
            image: docker
            command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 30']
